### ISSUE TITLE
OpenSource in TeamSite world

### ISSUE THREAD

**Issue by PiotrCzapla** [kaimallea/tsquery#2]
Hey,

It seems to me as a first attempt to share something in the TeamSite community, good work!

I'm looking to open source some of our libraries (on the java side) as well, but I'm really surprised that your nice library didn't pick up the pace. Have you tried to get some ppl. to contribute? On the devnet I only seen one thread with ppl requesting more "meat", instead offering the help to provide some contributions.

Did you follow up with them off public channels? Do you know if anyone is actually using your library?

I'm curious if there is any chance to get this stiff community to open up a bit and start sharing the stuff that is being developed in every TS shop I know. And I hoped that maybe you have some insights on this.  

Cheers,
Piotr

**Comment by kaimallea** [comment]
Hi,

Thanks for the feedback. I haven't worked with TeamSite in several years, as I no longer work for the company that used it. I doubt that my current employer will ever use TeamSite, so I can't say if/when I will ever work with TeamSite again.

Having said that, if someone wants to takeover this project, I'm happy to help them do so. :-)
